# Generated by Django 4.0.4 on 2022-05-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collective", "0004_alter_questionnaireitem_description_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="collective.questionnaireitem",
            ),
        ),
    ]
