# Generated by Django 4.0.5 on 2022-06-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collective", "0005_alter_answer_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collectives", models.IntegerField(default=0)),
                ("questions", models.IntegerField(default=0)),
                ("answers", models.IntegerField(default=0)),
                ("users", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
