# Generated by Django 4.1.5 on 2023-02-05 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collective", "0010_alter_questionnaireitem_collective"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="collective",
            name="name",
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name="collective",
            name="title",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="questionnaireitem",
            name="name",
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name="questionnaireitem",
            name="title",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="name",
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
