# Generated by Django 4.1.6 on 2023-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collective", "0011_alter_answer_user_alter_collective_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="collective_name",
            field=models.SlugField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="type",
            field=models.SlugField(blank=True, default="", max_length=250, null=True),
        ),
    ]
