# Generated by Django 4.1.6 on 2023-03-20 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collective", "0015_userinfo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInfo",
            new_name="UserDescription",
        ),
    ]
