# Generated by Django 4.1.6 on 2023-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collective", "0016_rename_userinfo_userdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="allow_register",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
